server:
  port: 8090
spring:
  datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/springboot_db?useUnicode=true&amp;characterEncoding=utf8
        username: root
        password: root
  output:
      ansi:
        enabled: always