server:
  port: 8090
spring:
  datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/springboot_db?useUnicode=true&amp;characterEncoding=utf8
        username: root
        password: root
mybatis:
  configuration:
  # 配置项：开启下划线到驼峰的自动转换，作用：将数据库字段根据驼峰规则自动注入到对象属性。
    map-underscore-to-camel-case: true
